# https://golangci-lint.run/usage/configuration/
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - cyclop
    - errname
    - funlen
    - gochecknoinits
    - goimports
