name: Test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Unit Tests
      run: |
        go test -v ./cmd/...
        go test -v ./config/...
        go test -v ./internal/...
        go test -v ./tools/...

    - name: Integration Tests
      run: go test -v ./test/integration/...